ALTER TABLE Barcodes ADD COLUMN needsSync INTEGER;

ALTER TABLE BarcodeTypes ADD COLUMN needsSync INTEGER;

ALTER TABLE Coupons ADD COLUMN needsSync INTEGER;

ALTER TABLE Customers ADD COLUMN needsSync INTEGER;

ALTER TABLE DiscountCards ADD COLUMN needsSync INTEGER;

ALTER TABLE Feedbacks ADD COLUMN needsSync INTEGER;

ALTER TABLE Shops ADD COLUMN needsSync INTEGER;
