ALTER TABLE Barcodes ADD COLUMN serverId INTEGER;

ALTER TABLE BarcodeTypes ADD COLUMN serverId INTEGER;

ALTER TABLE Coupons ADD COLUMN serverId INTEGER;

ALTER TABLE Customers ADD COLUMN serverId INTEGER;

ALTER TABLE DiscountCards ADD COLUMN serverId INTEGER;

ALTER TABLE Shops ADD COLUMN serverId INTEGER;
